version: "3"

services:
  rabbitmq:
    container_name: RABBIT_MQ
    image: rabbitmq:3.9-management    
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks: 
      - rabbitmq
      
networks:
  rabbitmq: